### ISSUE TITLE
Test with GoogleDocs exported .docx

### ISSUE THREAD

**Issue by adam3smith** [QualitativeDataRepository/Anno-REP#11]
Users report that didn't work

**Comment by qqmyers** [comment]
The change in #4 may have fixed the docx to pdf conversion itself but wouldn't have addressed any problem with extracting annotations. If we can get a sample that fails, I can take a look at that part.

**Comment by adam3smith** [comment]
Can no longer replicate

**Comment by adam3smith** [comment]
Current Stage (as of 2023-02-21) fails with this [Google-docs generated document](https://www.dropbox.com/s/98oi9j3gpvywenz/ATI_Testing_Doc_gdocs.docx?dl=0), not sure at which step. Anno-REP frontened returns a 404. Various other files on the same project work, so I'm pretty sure it's the file itself.

**Comment by qqmyers** [comment]
Should be fixed. There was a potential null pointer introduced in the changes to support better title finding. Deployed to dev/stage.

**Comment by adam3smith** [comment]
Thanks, confirmed!
