### ISSUE TITLE
Line Breaks lost from Word comments

### ISSUE THREAD

**Issue by adam3smith** [QualitativeDataRepository/Anno-REP#12]
As per the subject, we appear to be losing linebreaks from Word comments. 
See the `IT Revision 2022...` document shared today.

Here's what the first Word comment looks like
![image](https://user-images.githubusercontent.com/128986/214742305-d51e116a-5f5b-4331-8396-5334f4a75170.png)

And here it is extracted in Anno-REP:
![image](https://user-images.githubusercontent.com/128986/214743741-97dab577-99f8-4ab0-a486-fa83e89ceffe.png)

Best I can tell, all line breaks are affected.

**Comment by qqmyers** [comment]
Should be fixed on dev and stage. I've added a <br> element between paragraphs in the comments.

**Comment by adam3smith** [comment]
Thanks -- confirmed
