### ISSUE TITLE
Images in Word don't convert to PDF

### ISSUE THREAD

**Issue by adam3smith** [QualitativeDataRepository/Anno-REP#4]
E.g. figure 1 here: https://www.dropbox.com/s/xwcy8i5mrpskyzm/anno-rep-testing_paper.docx?dl=1

**Comment by qqmyers** [comment]
I replace the old converter with OpenOffice. This has to be installed separately, but once installed the JODC library I found will invoke it automatically to do the conversion. This change appears to fix this issue and the others related to docx to pdf conversion.

**Comment by adam3smith** [comment]
This doesn't appear to work in the test doc I sent you today (Figure 1, p. 35) -- it's no big deal if we can't get it to work, but if there's a toggle we can switch, it'd be nice.

**Comment by adam3smith** [comment]
OK, I tested again and this works, including caption. It doesn't work for charts embeded in Word docs, but I think we can skip those
