### ISSUE TITLE
Annotation text from PDF slightly off

### ISSUE THREAD

**Issue by adam3smith** [QualitativeDataRepository/Anno-REP#5]
E.g. https://www.dropbox.com/s/bzgh8pzsh98bykm/anno-rep-testing_paper.pdf?dl=1

First annotation: 
In PDF: non-profit Hypothesis,
In Hypothesis: non-profit Hypothesis, i

Second annotations: 
In PDF: One of us (Jacobs) piloted an ATI-supported exercise
In Hypothesis: One of us (Jacobs) piloted an ATI-supported exercise u

**Comment by adam3smith** [comment]
Since this often seems to be single letters, can we check on this and correct, perhaps?

**Comment by qqmyers** [comment]
I added code to drop trailing whitespace or whitespace plus final char that is the start of another word. This is in v0.0.3 which is on dev now.

**Comment by adam3smith** [comment]
Great, thanks, confirmed
