### ISSUE TITLE
.docx to PDF conversion does not embed font

### ISSUE THREAD

**Issue by adam3smith** [QualitativeDataRepository/Anno-REP#7]
https://www.dropbox.com/s/xwcy8i5mrpskyzm/anno-rep-testing_paper.docx?dl=1
gets converted from Gentium to a sans serif font. This may not be possible with proprietary fonts?

**Comment by qqmyers** [comment]
One work-around is to embed the fonts in the Word doc:
![image](https://user-images.githubusercontent.com/6731983/157935916-272cfc08-356d-4625-8346-1557cb625ef9.png)
This works for the example doc. Checking the 'only embed characters that are used' and 'don't embed common system fonts' items make the docx smaller and, at least for the example file, don't seem to affect the pdf.

For common ones, it may also be possible to have pdf load them from .ttf files - https://stackoverflow.com/questions/69554256/docx-to-pdf-conversion-using-opensagres-and-apache-poi-results-in-missing-symbol provides some guidance on how to setup a font provider.

**Comment by qqmyers** [comment]
I think this is fixed in v0.0.3 - see #4 for details. If there are still issues, I can investigate whether there are further conversion options to use.

**Comment by adam3smith** [comment]
Fixed, thanks!
